### ISSUE TITLE
Addition of clipboard features make package incompatible with headless environments

### ISSUE THREAD

**Issue by gryphonmyers** [jopemachine/case-cli#1]
Clipboard features may be useful for local development, but when using this package in CI, this package throws errors per this issue: https://github.com/sindresorhus/clipboardy/issues/63

Ideally the clipboard features would be opt-in or degrade gracefully in such environments

**Comment by jopemachine** [comment]
Thanks for pointing it out :)

I think this issue is resolved in `0.2.2`.

If you still have the problem, please reopen this issue and let me know.

**Comment by jopemachine** [comment]
> @jopemachine actually 0.2.2 still errors in GitHub Actions (different error now):
> 
> ```
> + case-cli@0.2.2
> updated 1 package in 5.911s
> Error: Unable to process file command 'env' successfully.
> Error: Invalid environment variable format 'Outline'
> ```

@gryphonmyers  I tested `0.2.2` on my headless ubuntu, cannot reproduce the error.

May I see the Github action?

**Comment by gryphonmyers** [comment]
This is the step where case-cli is used

```
- name: Compute Stack Name and Prefix
      shell: bash
      run: |
        npm i -g case-cli
        STACK_PREFIX=$(case-cli pascal $DOMAIN_NAME)
        echo "STACK_PREFIX=${STACK_PREFIX}" >> $GITHUB_ENV
        echo "STACK_NAME=${STACK_PREFIX}Stack" >> $GITHUB_ENV
      env:
        DOMAIN_NAME: ${{ inputs.domain-name }}
```

**Comment by jopemachine** [comment]
I made some fixes and released `0.3.4`.

And I tested 0.3.4 on CI using nodes 12, 14.

This is the workflow.

```
# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: case-cli test
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm i -g case-cli
      - run: case-cli -c=snake hello world
```

![2021-08-17_12-25-00](https://user-images.githubusercontent.com/18283033/129659020-acea5f98-316f-4998-85ce-e0b1ed6ee48c.png)

Could you test your workflow again using 0.3.4?
